// 2019-dev/components/Footer/index.vue
<template>
    <div class="footer">
        <div class="footer__contact">
            <div class="subtitle">聯絡我們</div>
            <a href="mailto:contact@mopcon.org" target="_blank" class="subtitle email">contact@mopcon.org</a>
        </div>

        <div class="footer__social">
            <div class="subtitle">在這裡找到 #MOPCON</div>
            <div class="icons">
                <a href="https://www.facebook.com/mopcon/" target="_blank" class="svg-fb">
                    <IconFB />
                </a>
                <a href="https://twitter.com/mopcon" target="_blank" class="svg-twitter">
                    <IconTwitter />
                </a>
                <a href="https://www.instagram.com/mopcon2019/" target="_blank" class="svg-ig">
                    <IconIg />
                </a>
                <a href="https://t.me/mopcon" target="_blank" class="svg-aircraft">
                    <IconAircraft />
                </a>
            </div>
        </div>
    </div>
</template>

<script>
import IconFB from "./svg/icon-fb.svg";
import IconIg from "./svg/icon-ig.svg";
import IconAircraft from "./svg/icon-aircraft.svg";
import IconTwitter from "./svg/icon-twitter.svg";

export default {
    name: "Footer",
    components: {
        IconFB,
        IconIg,
        IconAircraft,
        IconTwitter
    }
};
</script>

<style lang="scss" src="./style.scss" scoped></style>

// 2023-react/src/components/Layout/Footer.js
import classes from "./Footer.module.css";
import { ReactComponent as FaceBook } from "../asset/Icon/facebook.svg";
import { ReactComponent as Twitter } from "../asset/Icon/twitter.svg";
import { ReactComponent as Instagram } from "../asset/Icon/instagram.svg";
import { ReactComponent as Telegram } from "../asset/Icon/Telegram.svg";

const Footer = () => {
  return (
    <footer className={classes.container}>
      <p className={classes.logo}>
        M<span className={classes.textcolor}>O</span>PC
        <span className={classes.textcolor}>O</span>N
      </p>{" "}
      <a href="mailto:contact@mopcon.org" target="blank">
        <p>contact@mopcon.org</p>
      </a>
      <div className={classes.social}>
        <a target="blank" href="https://www.facebook.com/mopcon?locale=zh_TW">
          <FaceBook />
        </a>
        <a target="blank" href="https://twitter.com/mopcon">
          <Twitter />
        </a>
        <a target="blank" href="https://www.instagram.com/mopcon.tw/">
          <Instagram />
        </a>
        <a target="blank" href="/Telegram">
          <Telegram />
        </a>
      </div>
    </footer>
  );
};
export default Footer;
